# Generated by Django 3.0.5 on 2020-04-23 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BookModel',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('book_name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'xwx_book',
            },
        ),
    ]
